sudo: required
dist: trusty

language: c

matrix:
  include:
    - go: 1.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y autoconf automake pkg-config libdevmapper-dev libsqlite3-dev libvirt-dev qemu libvirt-bin -qq
  - cd `mktemp -d`
  - wget ftp://sources.redhat.com/pub/lvm2/LVM2.2.02.131.tgz
  - tar xf LVM2.2.02.131.tgz
  - cd LVM2.2.02.131
  - ./configure && make device-mapper && sudo make install

script:
  - cd ${TRAVIS_BUILD_DIR}
  - ./autogen.sh
  - ./configure
  - make
  - hack/test-cmd.sh
